# Generated by Django 2.0.2 on 2018-11-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('sfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomoerInfoDisplaySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional_code1_display_name', models.CharField(blank=True, max_length=512, verbose_name='任意コード1表示名')),
                ('optional_code1_active_flg', models.BooleanField(default=True, verbose_name='任意コード1表示フラグ')),
                ('optional_code2_display_name', models.CharField(blank=True, max_length=512, verbose_name='任意コード2表示名')),
                ('optional_code2_active_flg', models.BooleanField(default=True, verbose_name='任意コード2表示フラグ')),
                ('optional_code3_display_name', models.CharField(blank=True, max_length=512, verbose_name='任意コード3表示名')),
                ('optional_code3_active_flg', models.BooleanField(default=True, verbose_name='任意コード3表示フラグ')),
                ('workspace', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='register.Workspace')),
            ],
        ),
    ]
