# Generated by Django 2.0.2 on 2018-11-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('sfa', '0002_customoerinfodisplaysetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomoerInfoDisplaySetting',
            new_name='CustomerInfoDisplaySetting',
        ),
    ]
