# Generated by Django 2.0.2 on 2018-11-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0003_auto_20181107_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='tel_number1_duplicate_count',
            field=models.IntegerField(default=0, verbose_name='電話番号1の重複件数'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='tel_number2_duplicate_count',
            field=models.IntegerField(default=0, verbose_name='電話番号2の重複件数'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='tel_number3_duplicate_count',
            field=models.IntegerField(default=0, verbose_name='電話番号3の重複件数'),
        ),
    ]
